### POST /api/v1/signup
curl -X POST http://localhost:4000/api/v1/signup
-H 'Content-Type: application/json' 
-d '{
    "email": "test@test.com",
    "password": "password",
    "profile": {
        "name": "name lastname"
    }
}'

### GET /api/v1/login
http://localhost:4000/api/v1/login


### POST /api/v1/login 
curl -X POST http://localhost:4000/api/v1/login 
-H 'Content-Type: application/json' 
-d '{
    "email": "test@test.com",
    "password": "password"
}'

### GET /api/v1/account
http://localhost:4000/api/v1/account

### GET /api/v1/logout
http://localhost:4000/api/v1/logout

### GET /api/v1/authorizeRoute
http://localhost:4000/api/v1/authorizeRoute